apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-demo-app
  labels:
    app: aks-demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aks-demo-app
  template:
    metadata:
      labels:
        app: aks-demo-app
    spec:
      containers:
      - name: aks-demo-app
        image: Myacr7312.azurecr.io/aks-demo-app:latest  # Replace <ACR_NAME>
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: aks-demo-service
spec:
  type: LoadBalancer
  selector:
    app: aks-demo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
